### ISSUE TITLE
Tree visualization without the number text

### ISSUE THREAD

**Issue by markutz556** [matsengrp/gctree#119]
Hi,

Thanks for the tools and it's a great tools for BCR phylogeny analysis.

I generated a BCR tree image with pie chart and the image would become very wide if there are lots of groups (because there is a long list of group number to show on image and it has to be wide to avoid overlap). I think right now the image shows the texts of different groups by default. I wonder if you can make it as an option so that I can choose not to show the number text. Thanks.

Also I got errors when the node name is integer and no errors when the node name is string (same data).

Best,
Mike

**Comment by WSDeWitt** [comment]
Hi Mike,

I believe this is the section of code related to the pie chart and its labeling: https://github.com/matsengrp/gctree/blob/23a71520af416e5022981d9bf80f9a8511273859/gctree/branching_processes.py#L501-L518

You could try removing the lines about the text face `T` in a local clone of gctree, as a workaround.

We could eventually add a new option `abundance_labels` in the `render()` command (`True` by default), such that abundance labels are only produced if `abundance_labels=True`. We'd also apply this to the non-piechart labels on this line: https://github.com/matsengrp/gctree/blob/23a71520af416e5022981d9bf80f9a8511273859/gctree/branching_processes.py#L493

**Comment by markutz556** [comment]
Thanks for the response. I will do that.
