### ISSUE TITLE
tree rendering hangs when write directory doesn't exist.

### ISSUE THREAD

**Issue by jgallowa07** [matsengrp/gctree#131]
I'm not sure this is the case everywhere, but in my notebook, when I run the [tree.render](https://matsengrp.github.io/gctree/stubs/gctree.CollapsedTree.html#gctree.CollapsedTree.render) command, and feed it a path that doesn't exist, rather than throwing an error it just spins and kills my kernal. This took a while to figure out so I'd suggest an `assert` or `raise` somewhere [here](https://github.com/matsengrp/gctree/blob/10eabc7129f3f092eb84ac1b3b54a79a14cbfd0d/gctree/branching_processes.py#L454) maybe

**Comment by willdumm** [comment]
Thanks for this Jared, sorry it caused you trouble! I will be sure to fix this when I get back.
