### ISSUE TITLE
Installation or user idiocy problem 

### ISSUE THREAD

**Issue by vnminin** [matsengrp/gctree#36]
I am a complete idiot when it comes to python and conda, but after all installation steps, which didn't give any obvious errors, I got this:

(gctree) dhcp-v246-066:~/papers/gctree-phylo-ms$ scons --inference --input=example_input/150228_Clone_3-8.fasta --outdir=test --converter=tas --naiveID=GL --jobs=2
scons: Reading SConscript files ...
scons: done reading SConscript files.
usage: scons [OPTION] [TARGET] ...

SCons Error: no such option: --inference

**Comment by vnminin** [comment]
I am on Mac OS X 10.11.6, using python 2.7.14

**Comment by WSDeWitt** [comment]
@vnminin It looks like you are in the manuscript repo, rather than the `gctree` repo: https://github.com/matsengrp/gctree

**Comment by vnminin** [comment]
Thanks, @WSDeWitt. It worked once I cloned the repo and proceeded from the gctree directory. Maybe mention this in the Readme for idiots like me.

The example is still running on my machine, so maybe there will be more info on my terminal screen when everything is finished. In case I don't find this info, it would be helpful to add to this example information on how to process results (where are the trees, how to do bootstrap, how to plot GCtrees). I am sure you have this info somewhere, but having a completely worked out example in the Readme usually helps users a lot. Thoughts?

**Comment by vnminin** [comment]
Update: found lots of svg and pdf files in the test directory. Some of the files maybe self explanatory, but I think going though some output in the Readme Example makes sense.

**Comment by WSDeWitt** [comment]
There is a "_description of inference output files:_" in the **Quick Start** section. But maybe I should point readers there from the **Example** section.

**Comment by vnminin** [comment]
Eh, I think something more is needed. As a new user, I would still be very confused. Ideally, we want a brief, but complete walk through that starts with input sequences and ends with a beautiful of plot of GCtree with bootstrap support or whatever an immunologist would be interested in.
