### ISSUE TITLE
Fasta file with variable sequence length

### ISSUE THREAD

**Issue by NikaAb** [matsengrp/gctree#38]
Dear Mr. DeWitt,

I have a fasta file containing 21 DNA sequence with variable lengths. It is the output of Absim simulator. When I have used this file as the input of GC tree I got this error :

 ``` 
File "//anaconda/envs/gctree/lib/python2.7/site-packages/Bio/Align/__init__.py", line 550, in _append
    raise ValueError("Sequences must all be the same length")
```

Then I aligned my sequences and gave the alignment as the input of the GC tree; this time, I had the following error : 
```
 File "/Users/nikaabdollahi/tools/gctree-master/bin/phylip_parse.py", line 123, in disambiguate
    new_base = random.choice(ambiguous_dna_values[base])
KeyError: '-' 
```
Here are the files : 
[simulated.zip](https://github.com/matsengrp/gctree/files/3213075/simulated.zip)

I think that dnapars can variable length sequences with gap represented by '-', do have any idea how can I fix this problem? 

Thanks a lot!

**Comment by WSDeWitt** [comment]
Hi there! Thanks for bringing this to our attention. We assumed that SHM would not create indels—are you simulating indels arising from SHM and that is why you have variable sequence lengths? Or is it possible the sequences are from different VDJ clonal families?

With the above commit you should be ok with gap characters. Dnapars treats `-` as a 5th character state ([caution is urged](http://evolution.genetics.washington.edu/phylip/faq.html#indels)).

**Comment by NikaAb** [comment]
Many thanks for your commit, it works perfectly now!
Your assumption about SHM is right. I have a mixture of sequences coming from different stages of B cell development. In a cluster, sequences have the same VDJ clonal family, but they don't have necessarily the same length. That's why I was curious about using GCtree on aligned sequences.
