### ISSUE TITLE
use of color argument

### ISSUE THREAD

**Issue by cstrlln** [matsengrp/gctree#40]
Hi,
I'm trying to use the color argument when running scons with color file like:
cell_A,red
cell_B,red

but I get this:

Traceback (most recent call last):
  File "bin/deduplicate.py", line 152, in <module>
    main()
  File "bin/deduplicate.py", line 143, in main
    if len(colors_counts) == 1 and colors_counts[0][0] != None and colors_counts != []:
TypeError: 'dict_items' object is not subscriptable
scons: *** [test2/clone_943.phylip] Error 1
scons: building terminated because of errors.

any suggestions?
thank you

**Comment by WSDeWitt** [comment]
It looks like we missed this bit when upgrading to Python 3! Does the above commit resolve the bug for you?

**Comment by cstrlln** [comment]
that did it, thanks so much. Nice tool!

**Comment by WSDeWitt** [comment]
Great, thanks for bring this to our attention!
