### ISSUE TITLE
It is possible parallel processing in step python -u bin/gctree.py

### ISSUE THREAD

**Issue by Chuang1118** [matsengrp/gctree#42]
Dear Mr. DeWitt,
I want to ask you about increase the execution time, 
I have used your inference program for experimentail in put data in FASTA
Now, I have difficulties in running GCtree on my dataset containing ~2000 cells with a high range of abundance (more than 1000).
Version gctree-2.0.1 
```
scons --inference --input=/GCtree/FL338-471/FL338-471_cut.fasta --outdir=FL338-471_trio --naiveID=uca --jobs=8 \
--colorfile=/GCtree/FL338-471/FL338-471_color.csv --idlabel --quick
```
It is issue without an execution error.
--job parameters, it's not available in step "python gctree.py".
The code execution has been running more than 10 days, not finish yet.
Thanks!

Intermediate output: FL338-471_cut.phylip have 252 sequnces.

log file:
number of trees with integer branch lengths: 1
1 trees exhibit unobserved unifurcation from root. Adding psuedocounts to these roots
building likelihood cache for parameters (0.8997127468897244, 0.9240667759603199)
building likelihood cache for parameters (0.8997127468897244, 0.9240667759603199)
building likelihood cache for parameters (0.8997127617908856, 0.9240667759603199)
building likelihood cache for parameters (0.8997127468897244, 0.9240667908614811)
building likelihood cache for parameters (0.8997127468897244, 0.9240667759603199)
building likelihood cache for parameters (1e-06, 1e-06)

**Comment by WSDeWitt** [comment]
Hi, sorry you're having trouble! I'm not sure what's causing this, but suspect something funny is happening with parameter optimization. Are you able to share your `FL338-471_cut.fasta` or another input file that reproduces this issue?

**Comment by Chuang1118** [comment]
Thank you for your reply,
I have used miniconda environment magagement, installed jellyfish and used gctree-2.0.1 before launch.
In the attached file (tar.gz), you will find the following files:
* FL338-471_cut.fasta : contains the sequences aligned and with the same length(without "N" and gap).
* FL338-471_color.csv : color file to color the tree.

If I launch the analysis on the complete file (1858 sequences), it seems to take 30 days (estimation from the current state of the execution).
If I split FL338-471_cut.fasta in first 1000 sequences and 858 last sequences (+1 root sequence), time execution is around 30 minutes for each run and I get the results called (see in the tar.gz):
* first1000cells_gctree.inference.1.svg
* restcells_gctree.inference.1.svg

Could you please tell me how can I execute the tool on my 1858 sequence with an acceptable execution time?

Many thanks!

[question_github.tar.gz](https://github.com/matsengrp/gctree/files/4248879/question_github.tar.gz)

**Comment by WSDeWitt** [comment]
Hi @Chuang1118, I’m just seeing we never addressed this. Were you able to finish this run?

**Comment by Chuang1118** [comment]
Hello,

I have finish the run without error, but it take 27 days if I remember correctly. 
Very luckily,  I did not have the power cut :) 

Best,
Chuang

**Comment by WSDeWitt** [comment]
Congrats on the paper! Can you post a link? And thank you for citing our method. We have some new ideas in the works that I think should speed up likelihood caching in cases like yours.
