### ISSUE TITLE
About the output file when using the --bootstrap option

### ISSUE THREAD

**Issue by xvtyzn** [matsengrp/gctree#43]
Dear Mr. DeWitt,

First of all, thank you for creating a great software.
I would like to ask about the output when using the bootstrap option.

I am currently attempting to create a phylogenetic tree using a FASTA file containing 17 sequences. I used bootstrap to reference [your paper](https://academic.oup.com/mbe/article/35/5/1253/4893244) and make it more interpretable.
```
scons --inference --input=gctree_linage.fasta --outdir=out --converter=tas --naiveID=germ_naive --jobs=4 --bootstrap=100
```
When this option was used, the following file was created.
```
gctree.inference.abundance_rank.pdf
gctree.inference.bootstrap_compatibility.svg
gctree.inference.bootstrap_support.svg
gctree.inference.bootstrap_theta.pdf
gctree.inference.likelihood_rank.pdf
```
Perhaps I thought that gctree.information.bootstrap_compatibility.svg or gctree.information.bootstrap_support.svg would be available as a result file. These files show different bootstrap values. However, I wasn't sure which to choose.
I'm a beginner in phylogenetic tree theory, so if possible, I would appreciate it if you could answer.

Keigo

**Comment by WSDeWitt** [comment]
Hi, thanks for using our software, I hope it's useful!

What you probably want is the more standard bootstrap support as shown in `gctree.inference.bootstrap_support.svg`. The numbers on the branches indicate the number of bootstrapped trees containing this same bipartition of the taxa.

Bootstrap _compatibility_ as shown in `gctree.inference.bootstrap_compatibility.svg ` is a weaker condition than _support_. We compute the number of bootstrap trees that do not contain a split that is _incompatible_ with the given split from our original tree. Split compatibility is defined by having at least one empty intersection of a partition from the first split with a partition from the second split (so one split does not refute the other). More on this in [Semple and Steel, Phylogenetics (2003)](https://global.oup.com/academic/product/phylogenetics-9780198509424?cc=us&lang=en&).

**Comment by xvtyzn** [comment]
Thank you for the very helpful suggestions!
I'll follow your suggestions and make a selection of files!

Thank you!
