### ISSUE TITLE
Data inconsistency between simulation and inference

### ISSUE THREAD

**Issue by NikaAb** [matsengrp/gctree#44]
Dear GCtree team,

I have simulated a  BCR lineage and then ran GCtree inference on the simulated  FASTA file. 
In the simulated fasta file, there are no _simcell_134_ and _simcell_37_, but they are in the simulated nk file.

Simulated :
(simcell_223:1,simcell_224:3)**simcell_134:1**)_'simcell_221'_ 'simcell_219'_ 'simcell_222'_ 'simcell_226'_'simcell_220'_:1)**simcell_37:1**

In the inferred nk file, I have two numbers as sequence ids with no equivalent in the idmap file.

Inferred :
(seq37:1,seq38:3)**8:1**,seq34:2)seq35:1)**10:1**

Probably these sequences are the missing sequences in the fasta and idmap file. 

I wonder if you can help me to understand it. 

I send you the output of the simulation and the inference steps. [GCTREE_output.zip](https://github.com/matsengrp/gctree/files/5568899/GCTREE_output.zip)

Thanks a lot!

**Comment by WSDeWitt** [comment]
Hi! I believe this is a result of how repeated sequences are collapsed into one representative sequence for the purpose of phylogeny reconstruction. The fasta contains an entry for each cell (with an id for each cell). After collapsing by sequence identities, the groups of cells with the same sequence are assigned a new id, and an associated abundance.

Looking at the inferred and simulated tree svgs, there are 100 total cells in both cases, and this matches the 100 simulated cells in your fasta. So I think this is all ok.

**Comment by WSDeWitt** [comment]
Expanding on this a little: in the inferred tree newick file, the integer node IDs come from how phylip labels internal nodes of trees. To show the node labels corresponding to the idmap file, you might try the `--idlabel` option. If you want to manipulate and inspect the inferred collapsed trees programmatically, a better option is to access the `CollapsedTree` objects in the pickle file.

**Comment by NikaAb** [comment]
Dear @WSDeWitt,
Thanks for your clear explanation; it helped me a lot.
