### ISSUE TITLE
colors in hex

### ISSUE THREAD

**Issue by cstrlln** [matsengrp/gctree#47]
Is it possible to use colors in hex format? Tried e.g. #56B4E9 but didn't work
Thanks!

**Comment by WSDeWitt** [comment]
The allowed colors are those supported by ETE's [`CircleFace`](http://etetoolkit.org/docs/latest/reference/reference_treeview.html?highlight=circleface#ete3.CircleFace), so you should be able to RGB color codes, as well as [these](http://etetoolkit.org/docs/latest/reference/reference_treeview.html#ete3.SVG_COLORS) named colors. Does that get you what you need?

**Comment by cstrlln** [comment]
I'will try with the rgb color codes, thanks!
