### ISSUE TITLE
Plot are not generated due to a problem with Qt

### ISSUE THREAD

**Issue by Aurelien-Pelissier** [matsengrp/gctree#49]
qt.qpa.xcb: could not connect to display
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, minimal, minimalegl, offscreen, vnc, webgl, xcb.

**Comment by WSDeWitt** [comment]
Can you let me know what platform/OS you are working on?

**Comment by Aurelien-Pelissier** [comment]
Thank you for your help !

I am working with Ubuntu 20.04 LTS.

**Comment by WSDeWitt** [comment]
You may need to provide the flag `--xvfb` which will allow X rendering of ETE trees without X forwarding (i.e. on a remote machine). Does this solve your issue?
