### ISSUE TITLE
find identical mamaras in the tree

### ISSUE THREAD

**Issue by matsen** [matsengrp/gctree#53]
Find identical structures like this:

![image](https://user-images.githubusercontent.com/112708/129614400-fb7ce872-5cf0-4f83-9e76-0adf1a8a7a4f.png)

in the ETE-parsed version of the parsimony trees. @WSDeWitt will be your guide.

We'll call these structures "mamaras" for multi-samaras?

**Comment by willdumm** [comment]
Notes from today:
* About the labeled subsplit DAG representing parsimony trees:
    * We can add weight on DAG edges corresponding to mutation number. Can we use this to efficiently extract the max. parsimony trees from a DAG which inevitably expresses some trees which are not max. parsimony trees? Maybe [Edmonds' Algorithm](https://en.wikipedia.org/wiki/Edmonds%27_algorithm)?
    * As Erick suggested, we can plan to explore expanding ambiguity codes at runtime instead of adding extra nodes
    * We need to think about how to compute branching process parameter likelihood efficiently from a DAG
* About the idea of a subsplit DAG representing collapsed trees:
    * Other than accommodating multifunctions, this is a normal subsplit DAG
    * Resolve variable leaf sets issue by thinking of internal nodes as tips
    * Again, annotate edges, or tips, with mutation number, use this to distinguish 'leaf' tips from 'internal' tips
    * We need to think about how this DAG helps us make use of the spaceship factorization...
* In both, we could consider the case that there are different ways of distributing the sample abundance among collapsed tree nodes of the same genotype

**Comment by WSDeWitt** [comment]
Closed by #68

**Comment by matsen** [comment]
❤️ x 1000000

So excited to have @WSDeWitt and @willdumm making this happen!
