### ISSUE TITLE
Problem with Sequence IDs

### ISSUE THREAD

**Issue by fabio-t** [matsengrp/gctree#58]
Hi all, I'm really looking forward to using gctree for my b-cell analysis, as ancestral inference seems to come out of the box (as opposed to igphyml).

However, I'm struggling to understand exactly what kind of **input** gctree expects, because of Sequence IDs.

In super-short, I have a pipeline that from FASTQ files gives me clonal lineages (grouped by V and J gene, as well as 85% CDR3 similarity).

For each identified clonal lineage, I have plenty of inner "clones", each with a certain abundance. This is an extract from the muscle-aligned top clone:

```
>TGTGCAAGGGGGGGTAACTTACGTTTTTACTACTGG|CARGGNLRFYYW|157
GAGGTGAAGCTGGTGGAGTCTGGAGGAGGCTTGGTACAGCCTGGGGGTTCTCTGAGTCTC
TCCTGTGCAGCTTCTGGATTCACCTTCACTGATTACTACATGAGCTGGGTCCGCCAGCCT
CCAGGGAAGGCACTTGAGTGGTTGGGTTTTATTAGAAACAAAGCTAATGGTTACACAACA
GAGTACAGTGCATCTGTGAAGGGTCGGTTCACCATCTCCAGAGATAATTCCCAAAGCATC
CTCTATCTTCAAATGAATGCCCTGAGAGCTGAGGACAGTGCCACTTATTACTGTGCAAGG
------
>TGTGCAAGGGGGGGTAACTTACGTTTTGACTACTGG|CARGGNLRFDYW|3
GAGGTGAAGCTGGTGGAGTCTGGAGGAGGCTTGGTACAGCCTGGGGGTTCTCTGAGTCTC
TCCTGTGCAGCTTCTGGATTCACCTTCACTGATTACTACATGAGCTGGGTCCGCCAGCCT
CCAGGGAAGGCACTTGAGTGGTTGGGTTTTATTAGAAACAAAGCTAATGGTTACACAACA
GAGTACAGTGCATCTGTGAAGGGTCGGTTCACCATCTCCAGAGATAATTCCCAAAGCATC
CTCTATCTTCAAATGAATGCCCTGAGAGCTGAGGACAGTGCCACTTATTACTGTGCAAGG
------
>TGTGCAAGGGGGGGTAACTTACGTTTTTACTACTGG|CARGGNLRFYYW|2
GAGGTGAAGCTGGTGGAGTCTGGAGGAGGCTTGGTACAGCCTGGGGGTTCTCTGAGTCTC
TCCTGTGCAGCTTCTGGATTCACCTTCACTGATTACTACATGAGCTGGGTCCGCCAGCCT
CCAGGGAAGGCACTTGAGTGGTTGGGTTTTATTAGAAACAAAGCTAATGGTTACACAACA
GAGTACAGTGCATCTGTGAAGGGTCGGTTCACCATCTCCAGAGATAATTCCCAAAGCATC
CTCTATCTTCAAATGAATGCCCTGAGAGCTGAGGACAGTGCCACTTATTACTGTGCAAGG
------
>TGTGCAAGGGGGGGTAACTTACGTTTTCACTACTGG|CARGGNLRFHYW|1
GAGGTGAAGCTGGTGGAGTCTGGAGGAGGCTTGGTACAGCCTGGGGGTTCTCTGAGTCTC
TCCTGTGCAGCTTCTGGATTCACCTTCACTGATTACTACATGAGCTGGGTCCGCCAGCCT
CCAGGGAAGGCACTTGAGTGGTTGGGTTTTATTAGAAACAAAGCTAATGGTTACACAACA
GAGTACAGTGCATCTGTGAAGGGTCGGTTCACCATCTCCAGAGATAATTCCCAAAGCATC
CTCTATCTTCAAATGAATGCCCTGAGAGCTGAGGACAGTGCCACTTATTACTGTGCAAGG
------
>TGTGCAAGGGGGGGTAACTTACGTTTTTACTACTGG|CARGGNLRFYYW|1
GAGGTGAAGCTGGTGGAGTCTGGAGGAGGCTTGGTACAGCCTGGGGGTTCTCTGAGTCTC
TCCTGTGCAGCTTCTGGATTCACCTTCACTGATTACTACATGAGCTGGGTCCGCCAGCCT
CCAGGGAAGGCACTTGAGTGGTTGGGTTTTATTAGAAACAAAGCTAATGGTTACACAACA
GAGTACAGTGCATCTGTGAAGGGTCGGTTCACCATCTCCAGAGATAATTCCCAAAGCATC
CTCTATCTTCAAATGAATGCCCTGAGAGCTGAGGACAGTGCCACTTATTACTGTGCAAGG
------
```

I chose those kind of labels, because I'd like to see the CDR3 into the final plot. The final number in each header, is the abundance.

This makes the labels non-unique, because it's quite possible to have the same CDR3 and abundance in a clonal lineage.

- why can't `deduplicate` accept this, since it's going to assign a unique ID by itself anyway? (seq1, seq2..)
- if this is by design, I accept it. But then, by supplying unique IDs, I still lose the **abundance**. And if I use integer-id-as-abundance, then I still have the uniqueness issue, **because plenty of inner nodes will have the same size!**

Can you help with this? Do I skip deduplicate since I already have grouped the original reads?

**Comment by fabio-t** [comment]
OK, I've solved it by commenting out the id_set check in the `deduplicate.py`, which is not useful in my opinion:

```
        #if seq.id in id_set:
        #    raise ValueError("Sequence ID found multiple times:", seq.id)
        #else:
        #    id_set.add(seq.id)
```

I was able to run this on my data, although I lose the labels at least it works.

But it doesn't look like it does **ancestral inference**. It only rearranges observed sequences as nodes in the tree, it doesn't infer unobserved ancestors. What am I doing wrong?

**Comment by WSDeWitt** [comment]
Thanks for your enthusiasm about gctree (and sorry about the difficulties)! I agree the raise conditions on `seq.id` should go.

For the question about ancestral inference, what does your final tree look like? This is where you can see unobserved ancestors, if any were necessary for tree reconstruction. The output file `gctree.out.inference.1.svg` depicts the tree, and the `gctree.CollapsedTree` object is pickled in `gctree.out.inference.1.p`. Also, have you included the inferred naive ancestor for this clonal family?

**Comment by fabio-t** [comment]
Hi @WSDeWitt, in the few clonal lineages I've plotted, there were no nodes outside of those tagged as "seqX", so the original sequences after deduplication. How is an unobserved ancestor supposed to look like?

> Also, have you included the inferred naive ancestor for this clonal family?

You mean the germline as root, correct? If so, yes; actually, also wanted to ask you one thing about that: why the 10 characters limit?

**Comment by WSDeWitt** [comment]
Unobserved ancestors will look like small nodes in the tree without numbers. In this tree from the Quickstart page, the root and it's immediate descendant are unobserved, as well as 4 nodes in lower branches of the tree.
![](https://matsengrp.github.io/gctree/_images/gctree.out.inference.1.svg)
It is possible that the most parsimonious tree on your sequences does not require positing any unobserved sequences (i.e. that the ancestral sequences are all identical to observed leaves).

The 10 character limitation is inherited from the package [`phylip`](https://evolution.genetics.washington.edu/phylip.html), whose program [`dnapars`](https://evolution.genetics.washington.edu/phylip/doc/dnapars.html) we use to generate candidate parsimony trees.

**Comment by fabio-t** [comment]
Ah, OK.. that makes sense. Thanks a lot for the insight :)

I'm having a little trouble with computational time for larger trees, so I wonder if I better stick with `dnapars` or use `dnaml`. Final tree looks different too, in the small trees I have successfully produced. Any advice on this regard?

I'm also struggling to understand what `phyilip_parse` is, or if I need it at all - if you have time to explain it, I would be very grateful.

**Comment by WSDeWitt** [comment]
How many sequences are you making a tree on? If large, it can be quite a while, but can be sped up with the `--quick` option in [`mkconfig`](https://matsengrp.github.io/gctree/cli.html#mkconfig).

[`phylip_parse`](https://matsengrp.github.io/gctree/cli.html#phylip-parse) is for parsing the (not-so-easily machine readable) outfile from `dnapars`, and translating it to a forest of parsimony trees as a [`gctree.CollapsedForest`](https://matsengrp.github.io/gctree/stubs/gctree.CollapsedForest.html) object. You probably don't need to use this on the command line directly, as the module is used under the hood by [`gctree infer`](https://matsengrp.github.io/gctree/cli.html#infer).

**Comment by fabio-t** [comment]
I've been experiment with different node sizes, currently I'm trying with 50 nodes, with abundances from 10 to 600. My data varies a lot so I might have 200 nodes mostly singletons, or a few nodes with huge counts.

This specific one (50 nodes) took a few minutes with dnapars, but it's actually taking a lot with gctree (I imagine because I got many alternative trees). If it takes less than an hour it can be acceptable, although, not optimal. Any plans of making a multithreaded version of gctree?

**Comment by fabio-t** [comment]
Sorry for the back-to-back questions, but is there no way, apart from `quick`, to reduce the number of tree candidates? The 50-nodes run has just finished, I've got 52 inferences. I would have been happy to have only the top one saved, for example :)

**Comment by fabio-t** [comment]
Actually it seems like using `dnaml` + `quick` produces only one tree. Which suits me fine :) I hope this is "correct" though.

**Comment by WSDeWitt** [comment]
Looks like you found a solution here, so I will (belatedly) close
