### ISSUE TITLE
Any parallel or accelerated parameters?

### ISSUE THREAD

**Issue by liyi522** [matsengrp/gctree#66]
I think this tool is more suitable for B cell germline tree construction than other traditional tools.  

But I have some trouble when I infered the tree for a large number of sequences (~300 unique sequences). As your advise, I have add the parameters like "dnaml" and "quick". But it was not working, it have taken more than 6 hours and it is still working. Any other parameters for multithreaded or speeding up  of gctree? I would appreciate it if I could get an answer.

Looking forward your reply.

**Comment by WSDeWitt** [comment]
It sounds like the slow part of this process is the parsimony tree generation, which relies on the phylip package. It does take a long time with this many sequences, and there isn't much we can do about it in the immediate term, unfortunately.
