### ISSUE TITLE
accommodate ambiguous observed sequences

### ISSUE THREAD

**Issue by willdumm** [matsengrp/gctree#71]
At one time, gctree may have worked when fed observed sequences containing ambiguous bases. After #68, this is certainly no longer true.

The most straightforward way to fix this would require:
* modifying historydag to allow histories with different leaf label sets
* when leaf sequence ambiguities exist, disambiguating dnapars trees before passing them to historydag (since exploding hDAG leaf nodes invalidates child clade sets)
* modifying all annotations based on sequence keys to accommodate multiple disambiguations of the same observation
* modifying the history -> CollapsedTree validation process...

**Comment by willdumm** [comment]
For now, the error message in PR #72 is a good solution, but eventually this could be given a real fix, like the one in the issue description.

**Comment by psathyrella** [comment]
Just want to vote for finding a fix for this sooner than later if possible, unless I'm missing some way to work around it other than just tossing the sequences? Real data I see usually has some ambiguous bases and it'd be really nice to avoid losing all the other information in those seqs.

**Comment by willdumm** [comment]
I'm working on the first step to making this happen. Once I have that, it should just be a couple of days of work to fix this. For now, I _think_ that gctree <v4 may work on this data, although I don't think it was written with ambiguous observed sequences in mind.

**Comment by willdumm** [comment]
Actually, there are two ways this can happen.

The first option is basically what's outlined in the issue description. This would have the side effect that leaf sequences in inferred trees would not match the ambiguous observed sequences used as input. Instead, they would be disambiguations of those original ambiguous observed sequences. In some cases this disambiguation could be informative, in the sense that it's influenced by the other sequences and the structure of the tree. Other times the disambiguation could be misleading, since there could be many, many other possible disambiguations that aren't chosen.
If gctree pre-v4 worked on ambiguous sequences, it would have handled them in an analogous way.

The second option is:
* leave leaf sequences ambiguous (as observed)
* modify `explode` method to only explode internal nodes, and use this to disambiguate all internal nodes in the tree
* modify `hamming_distance` function to return the minimum possible distance when one sequence has ambiguities. This still requires that internal nodes are disambiguated to work properly, since a base cannot have two states simultaneously in the final tree. Such a hamming distance function would need to be used instead of sequence equality any time leaf nodes are evaluated for collapse (such as in `CollapsedTree.__init__`)
* modify the mutability distance function to accommodate ambiguous bases. Minimally, this could mean correctly picking out necessary mutations, given an ambiguous target sequence, and taking averages of substitution probabilities if necessary.


@psathyrella and @WSDeWitt, there are lots of implementation details here, but do you have any opinion about preserving the original ambiguous sequences vs disambiguating them, at times somewhat arbitrarily?

**Comment by psathyrella** [comment]
I think (with low confidence) that disambiguating would be useful. At least I'm imagining this would mean say we have two seqs that differ by like 1 point mutation, except one of them is missing a chunk at the start (so it's ambiguous) -- if I'm understanding right then this would result in the method assuming the missing bit corresponds to the other similar seq?

**Comment by willdumm** [comment]
Thanks, this is helpful. And yes, as long as at some of the sequences in the data set contain sequence information for the missing bit, then the inferred bases would be informed by those other sequences. I guess the inferred missing bases would only be completely uninformative if the same chunk is missing in every sequence in the data. It would probably be worth raising a warning about this situation.

**Comment by WSDeWitt** [comment]
Closed by #91
